#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""mythril.py: Bug hunting on the Ethereum blockchain
   http://www.github.com/ConsenSys/mythril
   """
from sys import exit
import mythril.interfaces.cli
import z3

if __name__ == "__main__":
   # s = z3.Optimize()
   # before_rlimit_count = 0
   # s.check()
   # after_rlimit_count = s.statistics().get_key_value("rlimit count")
   # print("run", after_rlimit_count-before_rlimit_count,  before_rlimit_count, after_rlimit_count)
   mythril.interfaces.cli.main()
   exit()

