#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""mythril.py: Bug hunting on the Ethereum blockchain
   http://www.github.com/ConsenSys/mythril
   """
from sys import exit
import mythril.interfaces.cli
import z3
import resource

if __name__ == "__main__":
   # s = z3.Optimize()
   # before_rlimit_count = 0
   # s.check()
   # after_rlimit_count = s.statistics().get_key_value("rlimit count")
   # print("run", after_rlimit_count-before_rlimit_count,  before_rlimit_count, after_rlimit_count)
   
   # Memory restrited by 4 GB
   four_GB= 4*1024*1024*1024
   soft, hard = resource.getrlimit(resource.RLIMIT_AS)    
   resource.setrlimit(resource.RLIMIT_AS, (four_GB, hard))
   
   mythril.interfaces.cli.main()
   exit()

